"""Export a per-mood fallback dish set for the API's offline path.

The API serves these when the intelligence service is unreachable, so they
must be real, deliverable catalog dishes with real prices — never a made-up
table. Re-run after editing dishes.json:

    python scripts/export_fallback.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.data.dishes import DISHES  # noqa: E402
from app.services.shortlist import mood_tags_for  # noqa: E402

OUT = ROOT.parent / "api" / "src" / "recommendations" / "fallback-dishes.ts"
MOODS = ["happy", "tired", "stressed", "adventurous", "celebrating", "relaxed"]
PER_MOOD = 15
# India-first: these cuisines are reliably deliverable on Swiggy.
CUISINE_RANK = {"indian": 0, "chinese": 1, "italian": 2, "american": 3}


def _eligible(mood: str):
    tags = mood_tags_for(mood)
    pool = [
        d for d in DISHES
        # The offline path has no live Swiggy image to fall back on.
        if d.tier == "main" and d.delivery_friendly and d.image_url and tags & set(d.mood_tags)
    ]
    pool.sort(key=lambda d: (CUISINE_RANK.get(d.cuisine, 9), d.price_inr))
    return pool[:PER_MOOD]


def _record(d) -> dict:
    return {
        "id": d.id,
        "name": d.name,
        "cuisine": d.cuisine,
        "category": d.category,
        "dietary_tags": d.dietary_tags,
        "allergens": d.allergens,
        "mood_tags": d.mood_tags,
        "price_inr": d.price_inr,
        "prep_time_min": d.prep_time_min,
        "calories": d.calories,
        "health_score": d.health_score,
        "image_url": d.image_url,
    }


def main() -> None:
    by_mood = {m: [_record(d) for d in _eligible(m)] for m in MOODS}
    for m, dishes in by_mood.items():
        assert len(dishes) >= 6, f"too few fallback dishes for {m}"
    body = json.dumps(by_mood, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// GENERATED by apps/intelligence/scripts/export_fallback.py — do not edit by hand.\n"
        "// Real catalog dishes the API serves when the intelligence service is down.\n\n"
        "export interface FallbackDish {\n"
        "  id: string;\n  name: string;\n  cuisine: string;\n  category: string;\n"
        "  dietary_tags: string[];\n  allergens: string[];\n  mood_tags: string[];\n"
        "  price_inr: number;\n  prep_time_min: number;\n  calories: number;\n"
        "  health_score: number;\n  image_url: string;\n}\n\n"
        f"export const FALLBACK_DISHES: Record<string, FallbackDish[]> = {body};\n"
    )
    print(f"wrote {OUT} ({sum(map(len, by_mood.values()))} entries)")


if __name__ == "__main__":
    main()
