// Character-to-Dishes mapping for fast, character-specific recommendations
// Used by backend characterRecommendationEngine to instantly return character-aligned dishes

export const CHARACTER_DISH_MAPPING: Record<string, string[]> = {
  joey: [
    "Pizza",
    "Meatball Subs",
    "Bagels",
    "Lasagna",
    "Fried Chicken",
    "Ribeye Steak",
    "Burgers",
    "Mac & Cheese",
    "Sandwiches",
    "Ice Cream",
    "Cappuccino",
    "Cookies",
    "Fries",
  ],
  chandler: [
    "Sandwiches",
    "Cheesecake",
    "Coffee",
    "Soft Pretzels",
    "Chinese Takeout",
    "Fries",
    "Chicken Wings",
    "Donuts",
    "Nachos",
    "Pizza",
    "Cookies",
    "Candy",
    "Late-night Snacks",
  ],
  michael: [
    "BBQ Ribs",
    "Bacon",
    "Wings",
    "Burgers",
    "M&Ms",
    "Soft Pretzels",
    "Pizza",
    "Chili",
    "Pasta",
    "Fried Chicken",
    "Party Mix",
    "Candy",
    "Hot Dogs",
  ],
  ted: [
    "Pasta Carbonara",
    "Risotto",
    "Steak",
    "Truffle Pasta",
    "Duck Confit",
    "Seafood Risotto",
    "Crepes",
    "Tiramisu",
    "Salmon",
    "Beef Wellington",
    "Wine Pairings",
    "Ossobuco",
    "Ravioli",
  ],
  barney: [
    "Wagyu Beef",
    "Caviar",
    "Oysters",
    "Filet Mignon",
    "Lobster",
    "Premium Sushi",
    "Aged Whiskey Steak",
    "Champagne",
    "Truffle Risotto",
    "Prime Rib",
    "Foie Gras",
    "Expensive Wine",
    "Shrimp Scampi",
  ],
  geet: [
    "Chole Bhature",
    "Golgappa",
    "Samosa",
    "Butter Chicken",
    "Paneer Tikka",
    "Chai",
    "Parathas",
    "Aloo Gobi",
    "Chaat",
    "Kheer",
    "Momos",
    "Tandoori Chicken",
    "Jalebi",
  ],
  munna: [
    "Pav Bhaji",
    "Dal Khichdi",
    "Butter Naan",
    "Rajma",
    "Home-Style Curries",
    "Tandoori Chicken",
    "Samosa",
    "Kachumber Salad",
    "Chikhalwali",
    "Dal Makhani",
    "Roti",
    "Biryani",
    "Chutney",
  ],
  rancho: [
    "Sprouts Salad",
    "Smoothie",
    "Dosa",
    "Idli",
    "Oats",
    "Quinoa",
    "Fruits",
    "Yogurt",
    "Healthy Wraps",
    "Brown Rice",
    "Steamed Vegetables",
    "Poha",
    "Upma",
  ],
  kabir: [
    "Andhra Biryani",
    "Spicy Curries",
    "Paneer Tikka Masala",
    "Tandoori Chicken",
    "Mutton Curry",
    "Spicy Kebabs",
    "Chikhalwali",
    "Dal Makhani",
    "Jalapeño Dishes",
    "Red Meat",
    "Fiery Vindaloo",
    "Spicy Tandoori",
    "Ghost Pepper Dishes",
  ],
  bunny: [
    "Sushi",
    "Pad Thai",
    "Falafel",
    "Pho",
    "Ramen",
    "Risotto",
    "Paella",
    "Dim Sum",
    "Mezze Platter",
    "Fusion Dishes",
    "Thai Curry",
    "Vietnamese Banh Mi",
    "Global Tapas",
  ],
};
