// GENERATED by apps/intelligence/scripts/export_fallback.py — do not edit by hand.
// Real catalog dishes the API serves when the intelligence service is down.

export interface FallbackDish {
  id: string;
  name: string;
  cuisine: string;
  category: string;
  dietary_tags: string[];
  allergens: string[];
  mood_tags: string[];
  price_inr: number;
  prep_time_min: number;
  calories: number;
  health_score: number;
  image_url: string;
}

export const FALLBACK_DISHES: Record<string, FallbackDish[]> = {
  "happy": [
    {
      "id": "in_007",
      "name": "Pav Bhaji",
      "cuisine": "indian",
      "category": "street_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "nostalgic",
        "comfort"
      ],
      "price_inr": 120,
      "prep_time_min": 15,
      "calories": 450,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1626132647523-66f5bf380027?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYXYlMjBCaGFqaXxlbnwwfHx8fDE3ODAzMTE4NTZ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_003",
      "name": "Masala Dosa",
      "cuisine": "indian",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "happy",
        "energetic",
        "comfort"
      ],
      "price_inr": 150,
      "prep_time_min": 15,
      "calories": 300,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNYXNhbGElMjBEb3NhfGVufDB8fHx8MTc4MDMxMTU2N3ww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_019",
      "name": "Rajma Chawal",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "comfort",
        "nostalgic",
        "happy"
      ],
      "price_inr": 150,
      "prep_time_min": 20,
      "calories": 400,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1668236534990-73c4ed23043c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxSYWptYSUyMENoYXdhbHxlbnwwfHx8fDE3ODM1MDE3NDN8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_005",
      "name": "Chole Kulche",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten"
      ],
      "mood_tags": [
        "happy",
        "comfort",
        "energetic"
      ],
      "price_inr": 180,
      "prep_time_min": 20,
      "calories": 580,
      "health_score": 4.5,
      "image_url": "https://images.unsplash.com/photo-1676976197340-be65999b7516?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaG9sZSUyMEt1bGNoZXxlbnwwfHx8fDE3ODAzMTE4MjF8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_010",
      "name": "Palak Paneer",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 280,
      "prep_time_min": 25,
      "calories": 380,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYWxhayUyMFBhbmVlcnxlbnwwfHx8fDE3ODAzMTIwNDR8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_025",
      "name": "Seekh Kebabs",
      "cuisine": "indian",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "celebratory",
        "happy",
        "adventurous"
      ],
      "price_inr": 300,
      "prep_time_min": 25,
      "calories": 380,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTZWVraCUyMEtlYmFic3xlbnwwfHx8fDE3ODM1MDE3NTR8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_001",
      "name": "Butter Chicken",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "happy"
      ],
      "price_inr": 350,
      "prep_time_min": 30,
      "calories": 520,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxCdXR0ZXIlMjBDaGlja2VufGVufDB8fHx8MTc4MDMxMTU2NHww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_011",
      "name": "Tandoori Chicken",
      "cuisine": "indian",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "adventurous",
        "celebratory"
      ],
      "price_inr": 350,
      "prep_time_min": 30,
      "calories": 450,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1727280376746-b89107a5b0df?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxUYW5kb29yaSUyMENoaWNrZW58ZW58MHx8fHwxNzgzNTAxNzI2fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_004",
      "name": "Chicken Biryani",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "celebratory",
        "happy",
        "comfort"
      ],
      "price_inr": 400,
      "prep_time_min": 50,
      "calories": 650,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQmlyeWFuaXxlbnwwfHx8fDE3ODAzMTE1NzJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_024",
      "name": "Chicken Vindaloo",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "adventurous",
        "stressed",
        "happy"
      ],
      "price_inr": 400,
      "prep_time_min": 35,
      "calories": 520,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "in_023",
      "name": "Mutton Curry",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "celebratory",
        "happy",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 40,
      "calories": 580,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1596797038530-2c107229654b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNdXR0b24lMjBDdXJyeXxlbnwwfHx8fDE3ODM1MDE3NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_003",
      "name": "Fried Rice",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "eggs",
        "soy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "nostalgic"
      ],
      "price_inr": 200,
      "prep_time_min": 15,
      "calories": 480,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxGcmllZCUyMFJpY2V8ZW58MHx8fHwxNzgwMzE2MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_008",
      "name": "Chicken Bao Bun",
      "cuisine": "chinese",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "happy",
        "nostalgic",
        "comfort"
      ],
      "price_inr": 200,
      "prep_time_min": 10,
      "calories": 280,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1670404160617-8ca76c8cc2be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQmFvJTIwQnVufGVufDB8fHx8MTc4MzUwMTY2N3ww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_009",
      "name": "Sesame Noodles",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "nuts",
        "soy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 250,
      "prep_time_min": 15,
      "calories": 440,
      "health_score": 6.0,
      "image_url": "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTZXNhbWUlMjBOb29kbGVzfGVufDB8fHx8MTc4MDMxNjI3Mnww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_001",
      "name": "Kung Pao Chicken",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "nuts",
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "energetic",
        "happy",
        "celebratory"
      ],
      "price_inr": 380,
      "prep_time_min": 20,
      "calories": 520,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1776729851079-686daa8ff9aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxLdW5nJTIwUGFvJTIwQ2hpY2tlbnxlbnwwfHx8fDE3ODAzMTYyNTh8MA&ixlib=rb-4.1.0&q=80&w=1080"
    }
  ],
  "tired": [
    {
      "id": "in_020",
      "name": "Idli Sambar",
      "cuisine": "indian",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "healthy",
        "relaxed",
        "comfort"
      ],
      "price_inr": 80,
      "prep_time_min": 15,
      "calories": 200,
      "health_score": 8.0,
      "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxJZGxpJTIwU2FtYmFyfGVufDB8fHx8MTc4MzUwMTc0NXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_008",
      "name": "Daal Rice",
      "cuisine": "indian",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "sick",
        "sad",
        "comfort",
        "stressed"
      ],
      "price_inr": 100,
      "prep_time_min": 15,
      "calories": 280,
      "health_score": 8.5,
      "image_url": "https://images.unsplash.com/photo-1727018953313-403d17215a1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxEYWFsJTIwUmljZXxlbnwwfHx8fDE3ODAzMTIwMzl8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_007",
      "name": "Pav Bhaji",
      "cuisine": "indian",
      "category": "street_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "nostalgic",
        "comfort"
      ],
      "price_inr": 120,
      "prep_time_min": 15,
      "calories": 450,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1626132647523-66f5bf380027?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYXYlMjBCaGFqaXxlbnwwfHx8fDE3ODAzMTE4NTZ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_009",
      "name": "Khichdi",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [],
      "mood_tags": [
        "sad",
        "sick",
        "comfort",
        "stressed"
      ],
      "price_inr": 120,
      "prep_time_min": 20,
      "calories": 320,
      "health_score": 8.0,
      "image_url": "https://images.unsplash.com/photo-1630409351211-d62ab2d24da4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxLaGljaGRpfGVufDB8fHx8MTc4MDMxMjA0MXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_003",
      "name": "Masala Dosa",
      "cuisine": "indian",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "happy",
        "energetic",
        "comfort"
      ],
      "price_inr": 150,
      "prep_time_min": 15,
      "calories": 300,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNYXNhbGElMjBEb3NhfGVufDB8fHx8MTc4MDMxMTU2N3ww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_019",
      "name": "Rajma Chawal",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "comfort",
        "nostalgic",
        "happy"
      ],
      "price_inr": 150,
      "prep_time_min": 20,
      "calories": 400,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1668236534990-73c4ed23043c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxSYWptYSUyMENoYXdhbHxlbnwwfHx8fDE3ODM1MDE3NDN8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_005",
      "name": "Chole Kulche",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten"
      ],
      "mood_tags": [
        "happy",
        "comfort",
        "energetic"
      ],
      "price_inr": 180,
      "prep_time_min": 20,
      "calories": 580,
      "health_score": 4.5,
      "image_url": "https://images.unsplash.com/photo-1676976197340-be65999b7516?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaG9sZSUyMEt1bGNoZXxlbnwwfHx8fDE3ODAzMTE4MjF8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_002",
      "name": "Dal Makhani",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "sad"
      ],
      "price_inr": 250,
      "prep_time_min": 25,
      "calories": 420,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1727018742095-14c9a05aa71a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxEYWwlMjBNYWtoYW5pfGVufDB8fHx8MTc4MDMxMTU2Nnww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_010",
      "name": "Palak Paneer",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 280,
      "prep_time_min": 25,
      "calories": 380,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYWxhayUyMFBhbmVlcnxlbnwwfHx8fDE3ODAzMTIwNDR8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_027",
      "name": "Paneer Tikka Masala",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "celebratory"
      ],
      "price_inr": 320,
      "prep_time_min": 25,
      "calories": 460,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYW5lZXIlMjBUaWtrYSUyME1hc2FsYXxlbnwwfHx8fDE3ODM1MDE3NTl8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_001",
      "name": "Butter Chicken",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "happy"
      ],
      "price_inr": 350,
      "prep_time_min": 30,
      "calories": 520,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxCdXR0ZXIlMjBDaGlja2VufGVufDB8fHx8MTc4MDMxMTU2NHww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_004",
      "name": "Chicken Biryani",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "celebratory",
        "happy",
        "comfort"
      ],
      "price_inr": 400,
      "prep_time_min": 50,
      "calories": 650,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQmlyeWFuaXxlbnwwfHx8fDE3ODAzMTE1NzJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_003",
      "name": "Fried Rice",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "eggs",
        "soy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "nostalgic"
      ],
      "price_inr": 200,
      "prep_time_min": 15,
      "calories": 480,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxGcmllZCUyMFJpY2V8ZW58MHx8fHwxNzgwMzE2MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_008",
      "name": "Chicken Bao Bun",
      "cuisine": "chinese",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "happy",
        "nostalgic",
        "comfort"
      ],
      "price_inr": 200,
      "prep_time_min": 10,
      "calories": 280,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1670404160617-8ca76c8cc2be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQmFvJTIwQnVufGVufDB8fHx8MTc4MzUwMTY2N3ww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_009",
      "name": "Sesame Noodles",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "nuts",
        "soy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 250,
      "prep_time_min": 15,
      "calories": 440,
      "health_score": 6.0,
      "image_url": "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTZXNhbWUlMjBOb29kbGVzfGVufDB8fHx8MTc4MDMxNjI3Mnww&ixlib=rb-4.1.0&q=80&w=1080"
    }
  ],
  "stressed": [
    {
      "id": "in_008",
      "name": "Daal Rice",
      "cuisine": "indian",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "sick",
        "sad",
        "comfort",
        "stressed"
      ],
      "price_inr": 100,
      "prep_time_min": 15,
      "calories": 280,
      "health_score": 8.5,
      "image_url": "https://images.unsplash.com/photo-1727018953313-403d17215a1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxEYWFsJTIwUmljZXxlbnwwfHx8fDE3ODAzMTIwMzl8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_009",
      "name": "Khichdi",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [],
      "mood_tags": [
        "sad",
        "sick",
        "comfort",
        "stressed"
      ],
      "price_inr": 120,
      "prep_time_min": 20,
      "calories": 320,
      "health_score": 8.0,
      "image_url": "https://images.unsplash.com/photo-1630409351211-d62ab2d24da4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxLaGljaGRpfGVufDB8fHx8MTc4MDMxMjA0MXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_002",
      "name": "Dal Makhani",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "sad"
      ],
      "price_inr": 250,
      "prep_time_min": 25,
      "calories": 420,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1727018742095-14c9a05aa71a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxEYWwlMjBNYWtoYW5pfGVufDB8fHx8MTc4MDMxMTU2Nnww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_010",
      "name": "Palak Paneer",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 280,
      "prep_time_min": 25,
      "calories": 380,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYWxhayUyMFBhbmVlcnxlbnwwfHx8fDE3ODAzMTIwNDR8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_027",
      "name": "Paneer Tikka Masala",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "celebratory"
      ],
      "price_inr": 320,
      "prep_time_min": 25,
      "calories": 460,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYW5lZXIlMjBUaWtrYSUyME1hc2FsYXxlbnwwfHx8fDE3ODM1MDE3NTl8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_001",
      "name": "Butter Chicken",
      "cuisine": "indian",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "happy"
      ],
      "price_inr": 350,
      "prep_time_min": 30,
      "calories": 520,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxCdXR0ZXIlMjBDaGlja2VufGVufDB8fHx8MTc4MDMxMTU2NHww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_024",
      "name": "Chicken Vindaloo",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "adventurous",
        "stressed",
        "happy"
      ],
      "price_inr": 400,
      "prep_time_min": 35,
      "calories": 520,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "in_023",
      "name": "Mutton Curry",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "celebratory",
        "happy",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 40,
      "calories": 580,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1596797038530-2c107229654b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNdXR0b24lMjBDdXJyeXxlbnwwfHx8fDE3ODM1MDE3NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_028",
      "name": "Andhra Biryani",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "adventurous",
        "celebratory",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 50,
      "calories": 700,
      "health_score": 4.5,
      "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "cn_009",
      "name": "Sesame Noodles",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "nuts",
        "soy"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 250,
      "prep_time_min": 15,
      "calories": 440,
      "health_score": 6.0,
      "image_url": "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTZXNhbWUlMjBOb29kbGVzfGVufDB8fHx8MTc4MDMxNjI3Mnww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "it_003",
      "name": "Chicken Carbonara",
      "cuisine": "italian",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "dairy",
        "eggs"
      ],
      "mood_tags": [
        "comfort",
        "happy",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 25,
      "calories": 620,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTcGFnaGV0dGklMjBDYXJib25hcmF8ZW58MHx8fHwxNzgwMzEyMDUyfDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_006",
      "name": "Grilled Cheese Sandwich",
      "cuisine": "american",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "sad",
        "comfort",
        "nostalgic"
      ],
      "price_inr": 180,
      "prep_time_min": 10,
      "calories": 420,
      "health_score": 4.0,
      "image_url": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxHcmlsbGVkJTIwQ2hlZXNlJTIwU2FuZHdpY2h8ZW58MHx8fHwxNzgwMzEyMTI2fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_021",
      "name": "Chicken Chili",
      "cuisine": "american",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "stressed",
        "comfort",
        "cold"
      ],
      "price_inr": 300,
      "prep_time_min": 20,
      "calories": 420,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1716535232842-d10da4eb33d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQ2hpbGl8ZW58MHx8fHwxNzgzNTAxNjkxfDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_002",
      "name": "Mac & Cheese",
      "cuisine": "american",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "sad",
        "comfort",
        "nostalgic"
      ],
      "price_inr": 350,
      "prep_time_min": 20,
      "calories": 580,
      "health_score": 3.5,
      "image_url": "https://images.unsplash.com/photo-1667499989723-c4ab9549d63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNYWMlMjAlMjYlMjBDaGVlc2V8ZW58MHx8fHwxNzgwMzEyMTE4fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "th_007",
      "name": "Thai Basil Chicken",
      "cuisine": "thai",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "energetic",
        "happy",
        "stressed"
      ],
      "price_inr": 300,
      "prep_time_min": 15,
      "calories": 420,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1627308595186-e6bb36712645?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxUaGFpJTIwQmFzaWwlMjBDaGlja2VufGVufDB8fHx8MTc4MDMxNjI4N3ww&ixlib=rb-4.1.0&q=80&w=1080"
    }
  ],
  "adventurous": [
    {
      "id": "in_025",
      "name": "Seekh Kebabs",
      "cuisine": "indian",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "celebratory",
        "happy",
        "adventurous"
      ],
      "price_inr": 300,
      "prep_time_min": 25,
      "calories": 380,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTZWVraCUyMEtlYmFic3xlbnwwfHx8fDE3ODM1MDE3NTR8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_011",
      "name": "Tandoori Chicken",
      "cuisine": "indian",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "adventurous",
        "celebratory"
      ],
      "price_inr": 350,
      "prep_time_min": 30,
      "calories": 450,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1727280376746-b89107a5b0df?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxUYW5kb29yaSUyMENoaWNrZW58ZW58MHx8fHwxNzgzNTAxNzI2fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_024",
      "name": "Chicken Vindaloo",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "adventurous",
        "stressed",
        "happy"
      ],
      "price_inr": 400,
      "prep_time_min": 35,
      "calories": 520,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "in_028",
      "name": "Andhra Biryani",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "adventurous",
        "celebratory",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 50,
      "calories": 700,
      "health_score": 4.5,
      "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "cn_006",
      "name": "Mapo Tofu",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "energetic",
        "adventurous"
      ],
      "price_inr": 280,
      "prep_time_min": 20,
      "calories": 380,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1769065647078-f067eb768035?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNYXBvJTIwVG9mdXxlbnwwfHx8fDE3ODAzMTYyNjZ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "vn_002",
      "name": "Vietnamese Chicken Sandwich",
      "cuisine": "thai",
      "category": "street_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten"
      ],
      "mood_tags": [
        "adventurous",
        "happy",
        "energetic"
      ],
      "price_inr": 200,
      "prep_time_min": 10,
      "calories": 320,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1600271886742-f049cd451bba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "vn_001",
      "name": "Chicken Pho",
      "cuisine": "thai",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "adventurous",
        "comfort",
        "relaxed"
      ],
      "price_inr": 350,
      "prep_time_min": 15,
      "calories": 380,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1631709497146-a239ef373cf1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "th_002",
      "name": "Green Curry",
      "cuisine": "thai",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "adventurous",
        "happy",
        "comfort"
      ],
      "price_inr": 380,
      "prep_time_min": 25,
      "calories": 520,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxHcmVlbiUyMEN1cnJ5fGVufDB8fHx8MTc4MDMxNjI3OXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "sp_001",
      "name": "Chicken Paella",
      "cuisine": "mediterranean",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten"
      ],
      "mood_tags": [
        "adventurous",
        "celebratory",
        "romantic"
      ],
      "price_inr": 800,
      "prep_time_min": 45,
      "calories": 580,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1534080564583-6be75777b70a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    }
  ],
  "celebrating": [
    {
      "id": "in_025",
      "name": "Seekh Kebabs",
      "cuisine": "indian",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "celebratory",
        "happy",
        "adventurous"
      ],
      "price_inr": 300,
      "prep_time_min": 25,
      "calories": 380,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxTZWVraCUyMEtlYmFic3xlbnwwfHx8fDE3ODM1MDE3NTR8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_027",
      "name": "Paneer Tikka Masala",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "stressed",
        "comfort",
        "celebratory"
      ],
      "price_inr": 320,
      "prep_time_min": 25,
      "calories": 460,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQYW5lZXIlMjBUaWtrYSUyME1hc2FsYXxlbnwwfHx8fDE3ODM1MDE3NTl8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_011",
      "name": "Tandoori Chicken",
      "cuisine": "indian",
      "category": "snack",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "adventurous",
        "celebratory"
      ],
      "price_inr": 350,
      "prep_time_min": 30,
      "calories": 450,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1727280376746-b89107a5b0df?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxUYW5kb29yaSUyMENoaWNrZW58ZW58MHx8fHwxNzgzNTAxNzI2fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_004",
      "name": "Chicken Biryani",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "celebratory",
        "happy",
        "comfort"
      ],
      "price_inr": 400,
      "prep_time_min": 50,
      "calories": 650,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDaGlja2VuJTIwQmlyeWFuaXxlbnwwfHx8fDE3ODAzMTE1NzJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_023",
      "name": "Mutton Curry",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "celebratory",
        "happy",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 40,
      "calories": 580,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1596797038530-2c107229654b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNdXR0b24lMjBDdXJyeXxlbnwwfHx8fDE3ODM1MDE3NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "in_028",
      "name": "Andhra Biryani",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "dairy"
      ],
      "mood_tags": [
        "adventurous",
        "celebratory",
        "stressed"
      ],
      "price_inr": 450,
      "prep_time_min": 50,
      "calories": 700,
      "health_score": 4.5,
      "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "sf_002",
      "name": "Butter Garlic Prawns",
      "cuisine": "indian",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "shellfish"
      ],
      "mood_tags": [
        "celebratory",
        "romantic"
      ],
      "price_inr": 2000,
      "prep_time_min": 20,
      "calories": 400,
      "health_score": 7.0,
      "image_url": "https://images.unsplash.com/photo-1559742811-822873691df8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxCdXR0ZXIlMjBHYXJsaWMlMjBQcmF3bnN8ZW58MHx8fHwxNzgzNTAxNzE2fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "cn_001",
      "name": "Kung Pao Chicken",
      "cuisine": "chinese",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "nuts",
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "energetic",
        "happy",
        "celebratory"
      ],
      "price_inr": 380,
      "prep_time_min": 20,
      "calories": 520,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1776729851079-686daa8ff9aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxLdW5nJTIwUGFvJTIwQ2hpY2tlbnxlbnwwfHx8fDE3ODAzMTYyNTh8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "it_001",
      "name": "Margherita Pizza",
      "cuisine": "italian",
      "category": "comfort_food",
      "dietary_tags": [
        "vegetarian"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "comfort",
        "celebratory"
      ],
      "price_inr": 350,
      "prep_time_min": 20,
      "calories": 600,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxNYXJnaGVyaXRhJTIwUGl6emF8ZW58MHx8fHwxNzgwMzEyMDQ5fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "it_007",
      "name": "Lasagne",
      "cuisine": "italian",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "dairy",
        "eggs"
      ],
      "mood_tags": [
        "comfort",
        "celebratory",
        "nostalgic"
      ],
      "price_inr": 500,
      "prep_time_min": 50,
      "calories": 700,
      "health_score": 4.5,
      "image_url": "https://images.unsplash.com/photo-1709429790175-b02bb1b19207?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxMYXNhZ25lfGVufDB8fHx8MTc4MDMxMjA1OXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_020",
      "name": "Chicken Hot Dogs",
      "cuisine": "american",
      "category": "street_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten"
      ],
      "mood_tags": [
        "happy",
        "celebratory"
      ],
      "price_inr": 150,
      "prep_time_min": 5,
      "calories": 290,
      "health_score": 3.0,
      "image_url": "https://images.unsplash.com/photo-1638368593249-7cadb261e8b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxIb3QlMjBEb2dzfGVufDB8fHx8MTc4MzUwMTY4OXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_011",
      "name": "Crispy Fried Chicken",
      "cuisine": "american",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "happy",
        "comfort",
        "celebratory"
      ],
      "price_inr": 350,
      "prep_time_min": 25,
      "calories": 680,
      "health_score": 3.5,
      "image_url": "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxDcmlzcHklMjBGcmllZCUyMENoaWNrZW58ZW58MHx8fHwxNzgzNTAxNjY5fDA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_012",
      "name": "Grilled BBQ Chicken Steak",
      "cuisine": "american",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "happy",
        "celebratory"
      ],
      "price_inr": 900,
      "prep_time_min": 20,
      "calories": 750,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxHcmlsbGVkJTIwQkJRJTIwQ2hpY2tlbiUyMFN0ZWFrfGVufDB8fHx8MTc4MzUwMTY3Mnww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_008",
      "name": "Chicken Philly Cheesesteak",
      "cuisine": "american",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "celebratory",
        "romantic"
      ],
      "price_inr": 1200,
      "prep_time_min": 15,
      "calories": 480,
      "health_score": 6.5,
      "image_url": "https://images.unsplash.com/photo-1734769853702-c7444c039c8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxQaGlsbHklMjBDaGVlc2VzdGVha3xlbnwwfHx8fDE3ODM1MDE2NjJ8MA&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "am_022",
      "name": "Baked Mac and Cheese with Chicken",
      "cuisine": "american",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "dairy"
      ],
      "mood_tags": [
        "romantic",
        "celebratory"
      ],
      "price_inr": 1200,
      "prep_time_min": 60,
      "calories": 680,
      "health_score": 5.0,
      "image_url": "https://images.unsplash.com/photo-1701484185547-a71576b65e1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxCYWtlZCUyME1hYyUyMGFuZCUyMENoZWVzZSUyMHdpdGglMjBDaGlja2VufGVufDB8fHx8MTc4MzUwMTY5NHww&ixlib=rb-4.1.0&q=80&w=1080"
    }
  ],
  "relaxed": [
    {
      "id": "in_020",
      "name": "Idli Sambar",
      "cuisine": "indian",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "healthy",
        "relaxed",
        "comfort"
      ],
      "price_inr": 80,
      "prep_time_min": 15,
      "calories": 200,
      "health_score": 8.0,
      "image_url": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxJZGxpJTIwU2FtYmFyfGVufDB8fHx8MTc4MzUwMTc0NXww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "hh_006",
      "name": "Brown Rice Bowl",
      "cuisine": "japanese",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [],
      "mood_tags": [
        "healthy",
        "relaxed"
      ],
      "price_inr": 150,
      "prep_time_min": 15,
      "calories": 250,
      "health_score": 8.5,
      "image_url": "https://images.unsplash.com/photo-1516684732162-798a0062be99?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "hh_002",
      "name": "Quinoa Bowl",
      "cuisine": "mediterranean",
      "category": "light_meal",
      "dietary_tags": [
        "vegetarian",
        "vegan"
      ],
      "allergens": [
        "nuts"
      ],
      "mood_tags": [
        "healthy",
        "relaxed"
      ],
      "price_inr": 300,
      "prep_time_min": 15,
      "calories": 350,
      "health_score": 9.5,
      "image_url": "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxRdWlub2ElMjBCb3dsfGVufDB8fHx8MTc4MzUwMTc2NHww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "vn_001",
      "name": "Chicken Pho",
      "cuisine": "thai",
      "category": "comfort_food",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [
        "gluten",
        "soy"
      ],
      "mood_tags": [
        "adventurous",
        "comfort",
        "relaxed"
      ],
      "price_inr": 350,
      "prep_time_min": 15,
      "calories": 380,
      "health_score": 7.5,
      "image_url": "https://images.unsplash.com/photo-1631709497146-a239ef373cf1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"
    },
    {
      "id": "sf_001",
      "name": "Grilled Salmon",
      "cuisine": "mediterranean",
      "category": "light_meal",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "healthy",
        "romantic",
        "relaxed"
      ],
      "price_inr": 600,
      "prep_time_min": 20,
      "calories": 350,
      "health_score": 9.0,
      "image_url": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxHcmlsbGVkJTIwU2FsbW9ufGVufDB8fHx8MTc4MzUwMTcxNHww&ixlib=rb-4.1.0&q=80&w=1080"
    },
    {
      "id": "fr_001",
      "name": "Herb-Roasted Chicken",
      "cuisine": "mediterranean",
      "category": "indulgent",
      "dietary_tags": [
        "non_veg"
      ],
      "allergens": [],
      "mood_tags": [
        "romantic",
        "celebratory",
        "relaxed"
      ],
      "price_inr": 900,
      "prep_time_min": 40,
      "calories": 620,
      "health_score": 5.5,
      "image_url": "https://images.unsplash.com/photo-1615557960916-5f4791effe9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5NjY0NjB8MHwxfHNlYXJjaHwxfHxIZXJiLVJvYXN0ZWQlMjBDaGlja2VufGVufDB8fHx8MTc4MzUwMTcwOHww&ixlib=rb-4.1.0&q=80&w=1080"
    }
  ]
};
